# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('number', models.IntegerField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('employmentBegin', models.DateField(blank=True)),
                ('employmentEnd', models.DateField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
