# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160917_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='dateTime',
        ),
    ]
