# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160917_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
