# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160917_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='employeeNo',
            new_name='employee',
        ),
    ]
