# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160918_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dateTime',
            new_name='begin',
        ),
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(default=None),
        ),
    ]
