# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161022_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='gelöscht'),
        ),
    ]
